# Generated by Django 4.2.6 on 2024-04-24 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_productcollection_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
